### ISSUE TITLE
Where's the source code?

### ISSUE THREAD

**Issue by mikwee** [man-schu/musedit#3]
You put a FLOSS license in the repo, yet the repo does not include any code! Why is that?

**Comment by man-schu** [comment]
Dear mikwee,

I don't understand your remark. The full source code is under the docs folder.

If there were no code, https://man-schu.github.io/dacapoeditor/ would not work.

**Comment by mikwee** [comment]
Okay, now I see it. Thanks!

P.S. Putting the source code in the `docs` directory is very confusing…

**Comment by man-schu** [comment]
Actually, I have seen that very often. It makes sense for me because it makes sure that it separates the pure code from all the rest. I might consider to investigate what is best practice.

**Comment by mikwee** [comment]
In many repositories, the directory that houses the source code is called `src`. I’d suggest that.

**Comment by man-schu** [comment]
I might do that in a future. Thanks for your remarks.
