### ISSUE TITLE
"Row" class renders as column on my iPad

### ISSUE THREAD

**Issue by mikwee** [man-schu/musedit#4]
Hey, it's me again!
When I open the app on my iPad, no matter which browser (as all of them use WebKit), the `row` class render as a column for some reason. For all I can tell WebKit supports the `float` attribute, which makes the row possible. So why could this be?
I hope you might have an idea.
Thanks.

**Comment by man-schu** [comment]
Hi,
Did you open the URL https://man-schu.github.io/dacapoeditor/ in Safari?

Sorry, I cannot reproduce the problem. I do not have an iPad, only an old iPhone as a test device. There it works fine.

Maybe you can send me a screenshot?

**Comment by man-schu** [comment]
I just uploaded the latest version of abcjs. Please check if that was the problem.

**Comment by mikwee** [comment]
Sadly this hasn’t changed the situation. This is what it looks like on Safari:
![IMG_7382](https://github.com/man-schu/dacapoeditor/assets/8478516/4c0b6765-2374-455f-878f-bf0c3fb459e9)
![IMG_7383](https://github.com/man-schu/dacapoeditor/assets/8478516/a131e7a1-9dee-4284-98b4-b0a01bbe5b36)

**Comment by man-schu** [comment]
Ah, apparently I didn't even understand the problem. The abcjs has indeed nothing to do. The problem must be in the style.css:
@media (min-width: 1080px)
The screenshots look like a very low resolution, isn't it? Can you tell me what is the resolution of your iPad?

**Comment by mikwee** [comment]
My iPad’s resolution is 2160×1620.

**Comment by man-schu** [comment]
I changed the max. width for 1 column from 1024 to 768px. Can you please try again?

**Comment by mikwee** [comment]
I'll try when I get back home.

**Comment by mikwee** [comment]
It works now, thanks!

**Comment by man-schu** [comment]
Glad to read that. Thanks for pointing out the problem.
